version: 2

workflows:
  version: 2
  test-all:
    jobs:
      - lint
      - unit-test-27:
          requires:
            - lint
      - functional-test-27:
          requires:
            - unit-test-27
      - unit-test-35:
          requires:
            - lint
      - functional-test-35:
          requires:
            - unit-test-35
            - functional-test-27
      - unit-test-36:
          requires:
            - lint
      - functional-test-36:
          requires:
            - unit-test-36
            - functional-test-27
            - functional-test-35
      - cleanup-functional-buckets:
          requires:
            - functional-test-27
            - functional-test-35
            - functional-test-36

jobs:
  lint:
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run: tox lint

  unit-test-27: &unit_test
    environment:
      TOXENV: py27
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run: tox test-unit

  unit-test-35:
    <<: *unit_test
    environment:
      TOXENV: py35

  unit-test-36:
    <<: *unit_test
    environment:
      TOXENV: py36

  functional-test-27: &functional_test
    environment:
      TOXENV: py27
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/bats-core/bats-core.git -b v1.0.2
            ./bats-core/install.sh /usr/local
            bats --version
      - run:
          command: |
            export TERM=xterm
            export AWS_DEFAULT_REGION=us-east-1
            export STACKER_NAMESPACE=cloudtools-functional-tests-$CIRCLE_BUILD_NUM
            export STACKER_ROLE=arn:aws:iam::459170252436:role/cloudtools-functional-tests-sta-FunctionalTestRole-1M9HFJ9VQVMFX
            tox test-functional

  functional-test-35:
    <<: *functional_test
    environment:
      TOXENV: py35

  functional-test-36:
    <<: *functional_test
    environment:
      TOXENV: py36

  cleanup-functional-buckets:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: tests/cleanup_functional_test_buckets.sh
